import Head from "next/head"

function Layout({ title, children }) {
  return (
    <>
      <Head>
        <title>James Ide | {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
      <footer>
        <div className="max-w-2xl mx-auto">
          <div className="flex flex-row justify-center p-2">
            <a
              className=" pr-2 font-bold hover:cursor-pointer hover:text-[#BED600] duration-500"
              href="https://www.linkedin.com/in/jamesaide/"
              target="#"
            >
              LinkedIn
            </a>
            <a
              className="pl-2 pr-2 font-bold hover:cursor-pointer hover:text-[#BED600] duration-500"
              href="https://github.com/JamesIde"
              target="#"
            >
              GitHub
            </a>
            <a
              className=" pl-2 pr-2 font-bold hover:cursor-pointer hover:text-[#BED600] duration-500"
              href="mailto:james.ide775@gmail.com"
              target="#"
            >
              Contact
            </a>
            <a
              className=" pl-2 pr-2 font-bold hover:cursor-pointer hover:text-[#BED600] duration-500"
              href="https://jamesaide.com"
              target="#"
            >
              Blog{" "}
            </a>
          </div>
          <h1 className="text-center mt-4 mb-6">
            Built with{" "}
            <span className="hover:cursor-pointer hover:text-[#BED600] duration-500">
              <a href="https://nextjs.org/" target="#">
                NextJS
              </a>
            </span>
            ,{" "}
            <span className="hover:cursor-pointer hover:text-[#BED600] duration-500">
              <a href="https://tailwindcss.com/" target="#">
                TailwindCSS{" "}
              </a>
            </span>{" "}
            and{" "}
            <span className="hover:cursor-pointer hover:text-[#BED600] duration-500">
              <a href="https://vercel.com/" target="#">
                Vercel{" "}
              </a>
            </span>
          </h1>
        </div>
      </footer>
    </>
  )
}
export default Layout
